name: Deploy to registry
on:
  push:
    tags:
      - jira/**

permissions:
  contents: read
  packages: none

jobs:

  attributes:
    name: Check module name and version
    uses: evoja/jira-dc-adopt/.github/workflows/atlas-mvn-attributes.yaml@a02c345105e3b7c6e8380478a29c9dcd4a52239e # same as @wf/mvn-attributes/05
    with:
      java_version: '8'
      root_proj_name: jira

  editorconfig-checker:
    name: ec
    needs: attributes
    uses: evoja/java-commons/.github/workflows/editorconfig-checker.yaml@5c9da1c159dc3a0dc1d4e07a2d3ddc28b8c28ed9 # same as @wf/editorconfig-checker/04

  ca-java:
    name: caj
    needs: attributes
    uses: evoja/jira-dc-adopt/.github/workflows/ca-atlas.yaml@a02c345105e3b7c6e8380478a29c9dcd4a52239e
    with:
      java_version: '8'
    permissions:
      contents: read
      packages: read

  deploy-java:
    name: dj
    needs: [attributes, editorconfig-checker, ca-java]
    uses: evoja/jira-dc-adopt/.github/workflows/deploy-atlas.yaml@a02c345105e3b7c6e8380478a29c9dcd4a52239e
    with:
      path_to_module: ${{needs.attributes.outputs.path}}
      java_version: '8'
    permissions:
      contents: read
      packages: write

